# Generated by Django 5.1.5 on 2025-01-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accuser',
            name='last_online',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/base_profile.png', upload_to='profile_pics/'),
        ),
    ]
