# Generated by Django 5.1.5 on 2025-02-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatss', '0004_groupchat_admin_groupchat_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='group_picture',
            field=models.ImageField(default='group_pictures/Default_group.svg', upload_to='group_pictures/'),
        ),
    ]
